name: CI & Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --tags origin

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install Babylon.js packages
        run: make pkg

      - name: Generate code
        run: make gen

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Release version
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "release@bot.com"
          git config --global user.name "Release Bot"
          make release
